### ISSUE TITLE
关于r2dbc如何整合国产数据库达梦

### ISSUE THREAD

**Issue by Patientrookie** [chenggangpro/reactive-mybatis-support#108]
我想问一下就是如何用这个reactive-mybatis-support如何连接达梦数据库并操作呢，目前有没有这样的计划或者有什么解决办法，我看项目分支都没有这个，因此问一下，感谢您的回答。

**Comment by chenggangpro** [comment]
MyBatis 只是ORM，具体连接数据库的操作是R2DBC驱动来执行的。目前R2DBC驱动只有几个大型数据库实现了[R2DBC-Drivers](https://r2dbc.io/drivers/)。如果想要通过R2DBC通过响应式的方式连接数据库，那么需要数据库方提供R2DBC驱动才可以。也就是说，需要达梦数据库适配R2DBC驱动，就像实现了JDBC驱动一样。

**Comment by Patientrookie** [comment]
好的，了解了，非常感谢您的回答
