### ISSUE TITLE
Return Optional<T>

### ISSUE THREAD

**Issue by cooper-lyt** [chenggangpro/reactive-mybatis-support#133]
If Query return null , current is return Mono.emty  can't map or other operation like this:

```
Mono<Tmod> getSomething(@Param("id") long id);
getSomething(1l).map(obj -> {
      if (obj == null) 
         ...
         can't work
});
```

So if return Optional<T> is best , but is not support in this version.

Optional is work fine in mabatis jdbc.

```
Mono<Optional<Tmod>> getSomething(@Param("id") long id);

getSomething(1l).map(obj -> obj.orElse(...));

```

**Comment by chenggangpro** [comment]
Hi~,
&ensp; &ensp;&ensp;Thanks to report this.
&ensp; &ensp;&ensp;In project reactor,`Mono` means one or empty signal in it's specification.If you look at those methods  which used to create a Mono in `Mono` class provided by `project-reactor` framework, you'll see a method as `public static <T> Mono<T> justOrEmpty(@Nullable Optional<? extends T> data)`.This method takes an `Optional<T>`  as its parameter and returns a new `Mono<T>`.Hence, in my opinion, a `Mono` represents one element signal or an empty signal, you don't need a`Mono<Optional<T>>` to represent an empty signal.
&ensp; &ensp;&ensp; I'll consider to support deserialize result to `Mono<Optional<T>>` type, but I really recommend to use `project-reactor` by following it's specification. 
&ensp; &ensp;&ensp;You can try the `Mono#switchIfEmpty(Mono<? extends T> alternate)` method  when the `Mono` is empty ,it would match your usage scenario.

**Comment by cooper-lyt** [comment]
Thanks!

"switchIfEmpty" is work for me.
