### ISSUE TITLE
Exception with useGeneratedKeys = false

### ISSUE THREAD

**Issue by cooperlyt** [chenggangpro/reactive-mybatis-support#137]
Exception with  useGeneratedKeys set to false.  same code set to true will be worked!

`Suppressed: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')`

```xml
...
        <dependency>
            <groupId>org.mariadb</groupId>
            <artifactId>r2dbc-mariadb</artifactId>
            <version>1.1.3</version>
        </dependency>
...
```
	
This is my test code in mapper:

``` java

//  create table TEST1(ID bigint NOT NULL AUTO_INCREMENT , NAME VARCHAR(10) NULL, PRIMARY KEY(ID));
  @Insert("INSERT INTO TEST1(NAME)" +
      " VALUES(#{name})")
  @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "ID")
  Mono<Integer> addTest1(Tmod mod);  // **This is Worked.**

  @Insert("INSERT INTO TEST1(NAME)" +
      " VALUES(#{name})")
  @Options(useGeneratedKeys =false)
  Mono<Integer> addTest1( @Param("name")String name); // **This throws  Exception**

//  create table TEST2(ID bigint NOT NULL  , NAME VARCHAR(10) NULL, PRIMARY KEY(ID));
  @Insert("INSERT INTO TEST2(ID,NAME)" +
      " VALUES(#{id},#{name})")
  Mono<Integer> addTest2(@Param("id") long id, @Param("name")String name);// **This throws  Exception too**
```

Return type change to `Mono<Long>` is same exception.

**Comment by cooperlyt** [comment]
I change result type to Mono<Void> 

```java
  @Insert("INSERT INTO TEST2(ID,NAME)" +
      " VALUES(#{id},#{name})")
  Mono<Void> addTest2(@Param("id") long id, @Param("name")String name);
```

throws exception:

`
	Suppressed: org.apache.ibatis.binding.BindingException: Mapper method 'pro.chenggang.example.reactive.mybatis.r2dbc.spring.mapper.Test2.addTest2' has an unsupported return type: class reactor.core.publisher.Mono
		at pro.chenggang.project.reactive.mybatis.support.r2dbc.binding.MapperMethod.rowCountResult(MapperMethod.java:151)
		at pro.chenggang.project.reactive.mybatis.support.r2dbc.binding.MapperMethod.execute(MapperMethod.java:100)
		at pro.chenggang.project.reactive.mybatis.support.r2dbc.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:160)
		at pro.chenggang.project.reactive.mybatis.support.r2dbc.binding.MapperProxy.invoke(MapperProxy.java:83)
		at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$OQMpyh45.addTest2(Unknown Source)
`

**Comment by cooperlyt** [comment]
I located this error is : 
     result.getRowsUpdated() .

[Release Notes for MariaDB Connector/R2DBC 1.1.3](https://mariadb.com/docs/xpand/release-notes/mariadb-connector-r2dbc/1-1-3/)

### Notable Changes

- To support the R2DBC 1.0.0 specification, the following implementation has been added or changed:

* Result.getRowsUpdated() now returns Mono<Long>. Prior to this release, Result.getRowsUpdated() returned Mono<Integer>.

**Comment by chenggangpro** [comment]
HI Copper,
     Thanks for reporting this.
      Since I've been busy for a long time, I haven't adapted the 1.0.0 R2DBC specification yet.I would finish adapting the 1.0.0 specification of R2DBC driver in this month.As long as I have time to do this.I'll also check the recently updates of `mybatis3` and `mybatis-spring`,and try to catch up official repository as soon as possible.

**Comment by chenggangpro** [comment]
Finished compatible with `r2dbc-spi` both `(0.9.1.RELEASE)` version and `1.0.0.RELEASE` version. See branch: [3.x](https://github.com/chenggangpro/reactive-mybatis-support/blob/3.x)
