### ISSUE TITLE
EnumTypeHandler to not being registered

### ISSUE THREAD

**Issue by cooperlyt** [chenggangpro/reactive-mybatis-support#140]
Mybatis Default  EnumTypeHandler is Not be auto register,
I Got a ClassCastException by Enum.
Need I Register it by manual ?
Or
Need I implement a R2dbcTypeHandlerAdapter?

**Comment by chenggangpro** [comment]
Yes, you should implement and register `R2dbcTypeHandlerAdapter` manually.I only implemented a few type's adapter in the source code .Those adapters are in `pro.chenggang.project.reactive.mybatis.support.r2dbc.executor.type.defaults` package.

**Comment by cooperlyt** [comment]
Thanks!
I will do it!
do you accept R2dbcEnumTypeHandlerAdapter PR?

**Comment by chenggangpro** [comment]
Perhaps it is better to implement `EnumTypeHandler ` in our own package? I found it is not all developers used standard `EnumTypeHandler` which set parameter and get result by Enum's name. Someone need to customize their own `EnumTypeHandler` to matching their own situation.So at the beginning ,I decided not to put the standard `EnumTypeHandler` into the source code.
On the other hand, the 1.0.0 of R2DBC specification had changed a few behaviour of setting parameters and getting results .In case of repetitive work, it would be better to refactor after completing the updates of 1.0.0 R2DBC specification.

**Comment by cooperlyt** [comment]
I got a problem when implementing the Enum TypeHandlerAdapter.

pro.chenggang.project.reactive.mybatis.support.r2dbc.executor.result.handler.DelegateR2dbcResultRowDataHandler:

```java
    private Optional<Class> getTypeHandlerArgumentType(TypeHandler typeHandler) {
        return Stream.of(typeHandler.getClass().getGenericSuperclass())
                .filter(type -> type instanceof ParameterizedType)
                .map(ParameterizedType.class::cast)
                .filter(parameterizedType -> TypeHandler.class.isAssignableFrom((Class) (parameterizedType.getRawType())))
                .flatMap(parameterizedType -> Stream.of(parameterizedType.getActualTypeArguments()))
                .map(Class.class::cast) //<----------- [Java generics type erasure] Throw exception 
                .findFirst();
    }
```
`Suppressed: java.lang.ClassCastException: Cannot cast sun.reflect.generics.reflectiveObjects.TypeVariableImpl to java.lang.Class`

**Comment by chenggangpro** [comment]
Ops, it doesn't support this.
I will consider to change the `R2dbcTypeHandlerAdapter#adaptClazz` method 's return signature to `java.lang.reflect.Type` .And refactor the whole `R2dbcTypeHandlerAdapter`'s behavior. I will look back to the original mybaits's source codes and see what's I missed before.

**Comment by cooperlyt** [comment]
Maybe should create a `R2dbcTypeHandlerAdapter` for each TypeHandler (include User custom TypeHandler),  AND join original TypeHandler to `R2dbcTypeHandlerAdapter#getResult` , That will solve this problem.

**Comment by chenggangpro** [comment]
Finished compatible with `r2dbc-spi` both `(0.9.1.RELEASE)` version and `1.0.0.RELEASE` version. See branch: [3.x](https://github.com/chenggangpro/reactive-mybatis-support/blob/3.x)
