### ISSUE TITLE
@AutoConfiguration instead of @Configuration

### ISSUE THREAD

**Issue by OverDrone** [chenggangpro/reactive-mybatis-support#148]
Recent version of spring boot 3.0 does not recognise and autostart R2dbcMybatisAutoConfiguration from mybatis-r2dbc-spring.
Class must be annotated with `@AutoConfiguration` instead of `@Configuration`. `spring.factories` still work but is deprecated too. Found some explanation here https://stackoverflow.com/a/75708952/1194528

**Comment by chenggangpro** [comment]
Finished compatible with `r2dbc-spi` both `(0.9.1.RELEASE)` version and `1.0.0.RELEASE` version. See branch: [3.x](https://github.com/chenggangpro/reactive-mybatis-support/blob/3.x)
