### ISSUE TITLE
class java.lang.Long cannot be cast to class java.lang.Integer

### ISSUE THREAD

**Issue by OverDrone** [chenggangpro/reactive-mybatis-support#150]
Subj exception thrown when using @Insert or @Update annotations. `DefaultReactiveMybatisExecutor.doUpdateWithConnection` contains bug: `result.getRowsUpdated()` returns Long but later collected as Integer: `Collectors.summingInt(Integer::intValue)`

**Comment by chenggangpro** [comment]
Thanks for reporting this.This is about the `r2dbc-spi` version 1.0.0, it changed return type from Integer to Long. But this project hasn't adapt to R2DBC specification 1.0.0 yet. When the adaptation is completed, it will be fixed.

**Comment by chenggangpro** [comment]
Finished compatible with `r2dbc-spi` both `(0.9.1.RELEASE)` version and `1.0.0.RELEASE` version. See branch: [3.x](https://github.com/chenggangpro/reactive-mybatis-support/blob/3.x)
