### ISSUE TITLE
ReactiveSqlSession.openSession()返回的ReactiveSqlSession是个单例对象

### ISSUE THREAD

**Issue by hua0424** [chenggangpro/reactive-mybatis-support#152]
我看源码发现DefaultReactiveSqlSession.openSession()返回的ReactiveSqlSession不是新创建的，而是一个全局变量。这样导致所有线程设置的事务等参数都是在同一个ReactiveSqlSession上进行的，会相互覆盖。另外，我发现并发的时候由于用的是同一个sqlSession，所有跟数据库的通讯都是串行执行的，无论并发量多大，数据库查到都只有一个连接。不知道能否优化？难道要动态创建新的DefaultReactiveSqlSession吗？

**Comment by chenggangpro** [comment]
1.  并不会相互覆盖，所有隔离级别配置都是基于context 来传递的，没有ThreadLoca在其中,而context 默认就线程隔离的，是关联整个pipeline的。 
2. 并发时，并不是串行的。核心的线程调度是依赖于底层netty的 eventloop,就像这个issue里描述的 [link](https://github.com/spring-projects/spring-data-r2dbc/issues/818#issuecomment-1449549771)，在实际业务使用中，并发量上升会出现由多个不同的 `reactor-tcp-nio-xxx` 线程日志 
3. 且同一个请求或者处理逻辑，不会与线程绑定。具体的可以看下reactor的specification 和 thread model

**Comment by hua0424** [comment]
确实是你说的那样，但是，是否开启事务withTransaction，自动提交autocommit等属性是在实例级别的，一个线程开事务另一个线程改为不开，那在交易开始时做上下文初始化的时候事务不就开启不成了吗

**Comment by chenggangpro** [comment]
当不在Spring环境中使用时（即，纯reactive mybatis 环境），ReactiveSqlSession是没有办法复用，openSession后续会更改为 new 一个新的session。实际执行食物时，是通过executor执行的。这里确实考虑不全面，多谢指出。当在Spring环境中时，由于事物是通过Spring对Connection进行管理的，所以 不会出现问题。

**Comment by chenggangpro** [comment]
Related test case : [ParallelTransactionTest](mybatis-r2dbc/src/test/java/pro/chenggang/project/reactive/mybatis/support/r2dbc/execution/transaction/parallel/ParallelTransactionTest.java)

**Comment by chenggangpro** [comment]
Finished compatible with `r2dbc-spi` both `(0.9.1.RELEASE)` version and `1.0.0.RELEASE` version.
