### ISSUE TITLE
能否适配一下Clickhouse

### ISSUE THREAD

**Issue by hylexus** [chenggangpro/reactive-mybatis-support#165]
**Clickhouse** 提供了 **r2dbc** 驱动，但是 `org.springframework.data.r2dbc.dialect.DialectResolver$R2dbcDialectProvide` 和 `org.springframework.r2dbc.core.binding.BindMarkersFactoryResolver` 可能需要适配一下。

```xml
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-client</artifactId>
    <version>0.7.1</version>
</dependency>
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-r2dbc</artifactId>
    <version>0.7.1</version>
</dependency>
```

**Comment by chenggangpro** [comment]
#### 1. 参考 [OraclePlaceholderDialect](https://github.com/chenggangpro/reactive-mybatis-support/blob/3.x/mybatis-r2dbc/src/main/java/pro/chenggang/project/reactive/mybatis/support/r2dbc/executor/placeholder/dialect/OraclePlaceholderDialect.java) 定义一个Clickhouse 的 PlaceholderDialect

```java
public class ClickhousePlaceholderDialect implements NamePlaceholderDialect {

    /**
     * The dialect name.
     */
    public static final String DIALECT_NAME = "Clickhouse";

    private static final Pattern PROPERTY_PATTERN = Pattern.compile("\\.|[^@:;/$\\d\\w_]");

    @Override
    public String name() {
        return DIALECT_NAME;
    }

    @Override
    public String getMarker() {
        return ":Ch_";
    }

    @Override
    public String propertyNamePostProcess(String propertyName) {
        if (Objects.isNull(propertyName) || propertyName.length() == 0) {
            return propertyName;
        }
        return PROPERTY_PATTERN.matcher(propertyName).replaceAll("_");
    }

}
```
*  Clickhouse 的参数绑定是通过`:name` 来实现的，不是通过index实现的，所以上面实现的是`NamePlaceholderDialect` 接口
*  这里marker是使用正则进行替换的，之所以使用`:Ch_`是为了尽量防止与参数中的参数名称出现冲突
* `DIALECT_NAME `需保持与Clickhouse 驱动中的ProductName一致：`com.clickhouse.r2dbc.connection.ClickHouseConnectionMetadata$getDatabaseProductName()` 

#### 2. 注册到 `R2dbcMybatisConfiguration` 中

```java
r2dbcMybatisConfiguration.getPlaceholderDialectRegistry().register(new ClickhousePlaceholderDialect());
```

#### 3. 如果是在SpringBoot环境中, 可以创建一个`R2dbcMybatisConfigurationCustomizer`类型的`bean`配置到Spring的上下文中

``` java
@Bean
public R2dbcMybatisConfigurationCustomizer r2dbcMybatisConfigurationCustomizer(){
    return r2dbcMybatisConfiguration -> r2dbcMybatisConfiguration.getPlaceholderDialectRegistry()
            .register(new ClickhousePlaceholderDialect());
}
```

#### 4. 后续会整理到Wiki中进行说明

**Comment by hylexus** [comment]
非常感谢。已经实现。
