### ISSUE TITLE
ResultHandler handle single nested query result returns null when there is only 1 nested result record

### ISSUE THREAD

**Issue by snyang** [chenggangpro/reactive-mybatis-support#41]
The work is great! thanks.
I just found that if there is a tag `collection` in resultMap, it will return empty.

I found  there is only 1 record, the code return null.

By using the project sample, after run the following sql:

```sql
delete from emp where dept_no in (2,3,4);
delete from dept where dept_no in (2,3,4);
```

The test case will failed.
```java
    @Test
    public void testGetDeptWithEmpCount() throws Exception {
        this.reactiveSqlSessionOperator.executeMany(
                this.deptMapper.selectDeptWithEmpList())
                .as(StepVerifier::create)
                .expectNextCount(1)
                .verifyComplete();
    }
```

I guess the problem is in the `mybatis-r2dbc\src\main\java\pro\chenggang\project\reactive\mybatis\support\r2dbc\executor\result\handler\DefaultReactiveResultHandler.java`
the `totalCount` is 0 in this case.

```java
    private List<Object> handleRowValuesForNestedResultMap(RowResultWrapper rowResultWrapper, ResultMap resultMap) throws SQLException {
        // ...
        this.resultHolder.addAll(resultHandler.getResultList());
        if (totalCount.intValue() != 0 && null == partialObject) {
            List<Object> holdResultList = new ArrayList<>(this.resultHolder);
            this.resultHolder.clear();
            return holdResultList;
        }
        return Collections.singletonList(DEFERRED);
}
```

**Comment by chenggangpro** [comment]
Hi @snyang ,
    I can't reproduce the problem.Is there something wrong with your `<resultMap>/<collection>` configuration? I thing there is a bug in your `<collection>` . You should remove the `javaType="java.util.List"` property.The `<collection>` represents a `List/Set/Collection`.
    In my test case [SimpleMapperTests#testGetDeptWithEmp](https://github.com/chenggangpro/reactive-mybatis-support/blob/5f8cce015ddea7eaaee27a16e50e56680b54f1c7/mybatis-r2dbc/src/test/java/pro/chenggang/project/reactive/mybatis/support/r2dbc/suite/SimpleMapperTests.java#L141) with [resultMap](https://github.com/chenggangpro/reactive-mybatis-support/blob/5f8cce015ddea7eaaee27a16e50e56680b54f1c7/mybatis-r2dbc/src/test/resources/mapper/DeptMapper.xml#L52) works propertly.

**Comment by snyang** [comment]
@chenggangpro I will try your suggestion and let you know the result.

**Comment by chenggangpro** [comment]
Cloud not find any bug in test case ,close issue

**Comment by snyang** [comment]
@chenggangpro I guess I found where the proble is , please see the issue description.

**Comment by chenggangpro** [comment]
Hi~,
    I find the bug, I'll fixed today,Thanks a lot
