### ISSUE TITLE
提供的例子reactive-mybatis-support-examples，驱动换成postgresql 连接postgreql 无法启动

### ISSUE THREAD

**Issue by stylesmile** [chenggangpro/reactive-mybatis-support#71]
提供的例子reactive-mybatis-support-examples，驱动换成postgresql 连接postgreql 无法启动

**Comment by chenggangpro** [comment]
1. 只换驱动是不可以的，需要修改对应的配置
2. 可以 checkout一下 `postgresql` 分支，我自测是用 `postgres:12` 这个镜像测试的，运行`reactive-mybatis-support-examples`的test-case前需要提前执行初始化脚本  `src/main/resources/test_prepare.sql` 
3. `reactive-mybatis-support-examples`仓库针对不同驱动的example是通过branch进行区分的
