### ISSUE TITLE
用官方例子spring boot 2.7.0和springboot 3.0.0都启动报错

### ISSUE THREAD

**Issue by stylesmile** [chenggangpro/reactive-mybatis-support#72]

**Comment by chenggangpro** [comment]
1. 官方`mybatis-spring` 适配`SpringBoot` 2.7.x 及以上的版本还没有release，目前这个项目也不支持, link: [`mybatis-spring`2.1.0](https://github.com/mybatis/spring/milestone/16)，目前最高支持`SpringBoot` 2.6.x
2. `R2dbc-bom` 新版本SPI发生变化，有些驱动没有适配，当所有驱动稳定后这个项目再支持适配
